version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-buster-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
        name: Install dependencies
        command: npm install
        working_directory: client

      - run:
        name: Unit test
        command: npm run test:unit
        working_directory: client

workflows:
  build:
    jobs:
      - build
