version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-buster-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - circleci-demo-{{ checksum "client/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - circleci-demo-
      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - save_cache:
          paths:
            - client/node_modules
          key: circleci-demo-{{ checksum "client/package-lock.json" }}

      - run:
          name: Unit test
          command: npm run test:unit
          working_directory: client

      - run:
          name: Prepare release
          command: bash prepare-release.sh

      - run:
          name: Release
          command: bash release.sh

workflows:
  build:
    jobs:
      - build
